### ISSUE TITLE
Misleading as well as useless

### ISSUE THREAD

**Issue by Sychic** [mindlesslydev/AntiRat#2]
Not only does this lead to false confidence (despite the disclaimer), half the checks don't even work.
All of the checks for method calls don't work as they won't show up in compiled class files.

### Solution
Just delete this repository. Any attempt at an "anti-rat" only further propagates the illusion of safety, leading to further damage.

**Comment by mindlesslydev** [comment]
Hello, thank you for the constructive criticism. Your observation surround the method calls is correct with the way I was checking this before however this has now been rectified. As for 'the illusion of safety' - I have made it very clear that this isn't 100% accurate although from my testing with this updated version does a fairly good job at detecting rats. If you still feel I should delete the repository, you are entitled to that view however I will be closing this issue now.

**Comment by Sychic** [comment]
This won’t work on any kind of obfuscated code, as well as being a very poor solution of trying to detect malware which steals access tokens.

**Comment by Sychic** [comment]
Also trying to parse java class files as text is just straight up stupid.

**Comment by Sychic** [comment]
As a developer in the skyblock community, you should know better than creating software that not only will hurt the end user by providing a false sense of security, but also one that could potentially ruin the reputation of legitimate mods.

**Comment by fireguy188** [comment]
Hello @Sychic , we added your skytils mod to our mods folder along with a test rat file to test your anti rat system. Considering that I was sent the token, your system is trash and you have no authority to comment on this one.

**Comment by Sychic** [comment]
> Hello @Sychic , we added your skytils mod to our mods folder along with a test rat file to test your anti rat system. Considering that I was sent the token, your system is trash and you have no authority to comment on this one.

It was never advertised as such, so I don’t see where the issue here is?

**Comment by fireguy188** [comment]
So you admit that your SkytilsSecurityManager.java file is useless then?

**Comment by CriticalGameEror** [comment]
@Sychic 
I think you should realise that Mindlessly created this as an attempt to help the skyblock community with the escalating issue of people being ratted. He created this because he wanted to help solve this issue. Yes, it isn't perfect and it may give false negatives and false positives but that gives you no right to tell him to delete the repository.

> This won’t work on any kind of obfuscated code, as well as being a very poor solution of trying to detect malware which steals access tokens.

- Most skyblock rats feature copy pasted code from repositories which isn't obfuscated. Mindlessly tested the ones that aren't obfuscated and they were detected. Sure, it doesn't work on all cases, but it works on most. Even some proper anti-viruses on the market don't pick up every virus that may be downloaded. This is why people have to also use common sense. This tool is meant to help reduce the chance of being ratted, not outright remove it. People should also use common sense and if they don't then they would get ratted anyway regardless of this tool.

> Also trying to parse java class files as text is just straight up stupid.

- Ok so its stupid. Why is it so stupid? What would you do to change it? Don't just say something is stupid and don't elaborate. Its just rude and disrespectful. If you took the time to post an issue about this repository then you clearly care about it being out there so help Mindlessly improve it instead of just calling it stupid.

> As a developer in the skyblock community, you should know better than creating software that not only will hurt the end user by providing a false sense of security, but also one that could potentially ruin the reputation of legitimate mods.

- See my 1st point about this. All anti-malware causes a false sense of security. Nothing protects you 100% of the time. People must use common sense as well. If they are truly worried then they should get a proper developer to look through the code and confirm it is safe. Additionally, how will this ruin the reputation of legitimate mods? A big mod like NEU and Skytils has been covered and checked so many times that there is no way that this tool would ruin their reputation. With smaller mods, proper developers can check their legitimacy which would be far more beneficial for the mod that this saying it might be safe. Again, people need to use their common sense.


I have never seen anyone tell anyone else to delete a project they made because it is bad. You have no right to. GitHub is a platform that is made for people to help each other by sharing improvements. If you or any other developers know a way that they can improve it then you should share it with mindlessly instead of telling him to delete his project.

**Comment by Sychic** [comment]
> So you admit that your SkytilsSecurityManager.java file is useless then?

That's not even the point of that file...

**Comment by Sychic** [comment]
> @Sychic I think you should realise that Mindlessly created this as an attempt to help the skyblock community with the escalating issue of people being ratted. He created this because he wanted to help solve this issue. Yes, it isn't perfect and it may give false negatives and false positives but that gives you no right to tell him to delete the repository.

This is not the way you should be trying to help. In the end, the only real solution to token logging is educating people on how these types of programs spread and how to avoid them.  A great example of this is @ILikePlayingGames's Skyblock Mod Safety repository (https://github.com/ILikePlayingGames/SkyblockModSafety)

> > This won’t work on any kind of obfuscated code, as well as being a very poor solution of trying to detect malware which steals access tokens.
> 
> * Most skyblock rats feature copy pasted code from repositories which isn't obfuscated. Mindlessly tested the ones that aren't obfuscated and they were detected. Sure, it doesn't work on all cases, but it works on most. Even some proper anti-viruses on the market don't pick up every virus that may be downloaded. This is why people have to also use common sense. This tool is meant to help reduce the chance of being ratted, not outright remove it. People should also use common sense and if they don't then they would get ratted anyway regardless of this tool.

With the amount of token loggers that I've seen, the vast majority of them are obfuscated through usage of either simple base64 encoding of the webhook url or by a full string obfuscation method.

> > Also trying to parse java class files as text is just straight up stupid.
> 
> * Ok so its stupid. Why is it so stupid? What would you do to change it? Don't just say something is stupid and don't elaborate. Its just rude and disrespectful. If you took the time to post an issue about this repository then you clearly care about it being out there so help Mindlessly improve it instead of just calling it stupid.

Anyone worth their grain of salt working with java would know why in a second.

> 
> > As a developer in the skyblock community, you should know better than creating software that not only will hurt the end user by providing a false sense of security, but also one that could potentially ruin the reputation of legitimate mods.
> 
> * See my 1st point about this. All anti-malware causes a false sense of security. Nothing protects you 100% of the time. People must use common sense as well. If they are truly worried then they should get a proper developer to look through the code and confirm it is safe. Additionally, how will this ruin the reputation of legitimate mods? A big mod like NEU and Skytils has been covered and checked so many times that there is no way that this tool would ruin their reputation. With smaller mods, proper developers can check their legitimacy which would be far more beneficial for the mod that this saying it might be safe. Again, people need to use their common sense.

Again, see my response to your first point. Not all anti-malware creates a false sense of security as there are legitimate uses for such tools. Yes, nothing is 100% secure; yes, people must use common sense. But you should not be propagating the illusion of safety through something that looks like it was thrown together for your AP CS project. Your so called "proper developers" also simply don't have enough time to look through every single jar on the internet just to make sure people are safe. There's just too many people making content for the internet to try and cover it all. No matter how far your reach, there's always corners you cannot see.

>
> I have never seen anyone tell anyone else to delete a project they made because it is bad. You have no right to. GitHub is a platform that is made for people to help each other by sharing improvements. If you or any other developers know a way that they can improve it then you should share it with mindlessly instead of telling him to delete his project.

The way to improve this project is to remove it and instead educate people. You're trying to solve a severed arm with a band aid and a pat on the back.

**Comment by fireguy188** [comment]
> > So you admit that your SkytilsSecurityManager.java file is useless then?
> 
> That's not even the point of that file...

Then explain to me the point of line 69, to me it seems to be checking if the web socket is allowed to do it's stuff based on the URL. It looks like you are attempting to block common rat links such as discord.com, ipify.org and pastebin.com as well as a few others, and then running loadessential() which shuts down Minecraft.

**Comment by My-Name-Is-Jeff** [comment]
Hi there @fireguy188 !

I'm the other developer for Skytils along with Sychic. The "system" you are complaining about is infact mine.

The name "Skytils security manager" does not imply any actual security, it is merely the name of the class following a sort of convention. The main purpose of the class is to close the game when it fails to load. We have never made any sort of guarantee or claim that advertises to protect against authentication stealers. Such a guarantee is impossible and lulls the user into a false sense of security. As for why the "system fails," the purpose is for deterrence and to provide better user experience, as the game often freezes due to poorly designed malware. Many prevention measures that you are proposing would interfere with the game and therefore user experience. I am unaware where the "web socket check" is either.

If you want my perspective on this project, I think that mindlessly has good intentions which I respect, but unfortunately I don't agree with the methods. As you have seen before, the first version didn't seem to work, probably due to an oversight made by mindlessly which was corrected. The reason why failed detections are harmful is because the user is probably not going to investigate further than what the "trusted program" says. For example, a common tactic used by bad actors is to send a link of an antivirus result with zero detections, such as VirusTotal. Additionally, since there are false positives, even though they may be inevitable, this will teach the user to ignore legitimate detections which defeats the purpose of the program as they will not trust the results.

**Comment by CriticalGameEror** [comment]
Thank you @Sychic and @My-Name-Is-Jeff for your very respectful responses. I do see your point of views and I now do agree with what you are saying. Education is the best course of action, it always is in situations like this. I also realise that not all developers have time to look through every mod to see if it is safe.

> The reason why failed detections are harmful is because the user is probably not going to investigate further than what the "trusted program" says. For example, a common tactic used by bad actors is to send a link of an antivirus result with zero detections, such as VirusTotal.
- This specific point also allowed me to actually realise what damage could be done, so I would like to thank you for this.

I just felt that the original opening to this issue was very blunt and I felt I needed to say something about the original tone that this conversation was going down. I am happy that we ended with a more in-depth and respectful discussion.

Just one more note, 

> > > Also trying to parse java class files as text is just straight up stupid.
> > 
> > 
> > 
> > * Ok so its stupid. Why is it so stupid? What would you do to change it? Don't just say something is stupid and don't elaborate. Its just rude and disrespectful. If you took the time to post an issue about this repository then you clearly care about it being out there so help Mindlessly improve it instead of just calling it stupid.
> 
> Anyone worth their grain of salt working with java would know why in a second.
- I don't understand why parsing java class files as text would necessary be bad. I'm not trying to disagree with you. I just want to learn about why it is a bad idea since you know more than me.
